### ISSUE TITLE
ProtofFlux browse node search type bug.

### ISSUE THREAD

**Issue by chaixshot** [BlueCyro/CherryPick#21]
Same with attach component browse.

https://github.com/user-attachments/assets/26d66f8f-68d8-46e6-81a8-b348a6b80d0a

![image](https://github.com/user-attachments/assets/1951f8bc-c768-4269-b42d-ca438bd1b309)

**Comment by Krzeszny** [comment]
Same for IsNull and NotNull. They're unusable if you take them from the CherryPick browser.

@chaixshot btw, nice Advanced Toolgun :) It looks like you made it a multitool before I did. I'm still improving the visual effects, currently working on version 0.5. But why is the drum constantly rotating?

**Comment by chaixshot** [comment]
> @chaixshot btw, nice Advanced Toolgun :) It looks like you made it a multitool before I did. I'm still improving the visual effects, currently working on version 0.5. But why is the drum constantly rotating?

It broken after game update but it fixed in update 2024.7.15.917.
